# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=100, verbose_name='标题')),
                ('a_info', models.CharField(max_length=300, verbose_name='简介')),
                ('a_content', models.TextField(verbose_name='内容')),
                ('a_img', models.ImageField(upload_to='uploads', verbose_name='图片')),
                ('a_addtime', models.DateField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'art',
                'ordering': ['-a_addtime'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100, verbose_name='标签名')),
                ('t_info', models.CharField(max_length=200, verbose_name='标签描述')),
                ('t_addtime', models.DateField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Tag'),
        ),
    ]
