# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-a_addtime'], 'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='art',
            name='a_addtime',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='t_addtime',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
